### ISSUE TITLE
SMU messaage ids documentation

### ISSUE THREAD

**Issue by sibradzic** [FlyGoat/ryzen_nb_smu#1]
hi! Excellent info on SMU message IDs, I was looking for such info for long time! Can you please share where did get the information from?

How can one query the default values for various parameters, for example; `UlvVidOffset` or `VddOffVid`?

**Comment by FlyGoat** [comment]
Hmmm. I don't know either.
That's all I can get.

**Comment by sibradzic** [comment]
Thnx, please share more info if you can.
